spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      path: /h2
      enabled: true
    datasource:
      url: jdbc:h2:mem:test
server:
  servlet:
    encoding:
      force-response: true

